### ISSUE TITLE
Unexpected EOF when pressing enter to begin plot

### ISSUE THREAD

**Issue by digitalman2112** [storborg/axibot#42]
## Bug

User presses enter to begin a plot, this error is displayed

Press enter to begin.
Traceback (most recent call last):
  File "/usr/local/bin/axibot", line 9, in <module>
    load_entry_point('axibot==0.0.2', 'console_scripts', 'axibot')()
  File "/usr/local/lib/python2.7/dist-packages/axibot/cmd.py", line 180, in main
    return opts.function(opts)
  File "/usr/local/lib/python2.7/dist-packages/axibot/cmd.py", line 123, in plot
    input("Press enter to begin.")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Note, changing input("Press enter to begin.") to raw_input allows me to plot with no issues

## SVG File

Issue is NOT SVG dependent 

## Your Environment

* Axibot version (git sha1 hash): latest from master
* Axidraw version (1,2 or 3): 3
* Eibotboard version: Recent, but haven't verified; firmware 2.5.1
* Operating System and version: Latest Raspbian (fresh download)
* Python version:2.7

**Comment by pwicks86** [comment]
Not sure what's going on here, since we already use the six version of `input`, which should resolve this issue. Additionally, I get syntax errors when running under python 2.7 before I can even get to this point, further investigation is needed.

**Comment by MoritzStefaner** [comment]
I get the same error over here, OS X 10.12.6, python 2.7.
